spring.application.name=Restful_Api

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# File-based H2 Database
spring.datasource.url=jdbc:h2:file:/Users/henzlo/Documents/githuub/Spring_boot_learnign/db
spring.datasource.driverClassName=org.h2.Driver

# Custom Credentials
spring.datasource.username=henzloDB
spring.datasource.password=henzlo123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.boot.autoconfigure=DEBUG